version: '3.8'
services:
  bill_gateway_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8180:8180
    volumes:
      - .:/app
    networks:
      - bill-network
networks:
  bill-network:
    external: true
